server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - regex: # parse the app name from the filename
      source: filename
      expression: '/var/log/(?P<app_name>[^/]+)/current'
  - regex: # pull any structured json from the log
      expression: '^.*\s*(?P<json>{.*}).*$'
  - json:
      source: json
      expressions:
        app_module: app_module
        app_name: app_name
        app_version: app_version
        msg: msg
        log_type: type
  - labels:
      app: app_name
      app_module:
      app_name:
      app_version:
      msg:
      log_type:
  static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*/current
        app: __path__
        